config/routes.rb
Rails.application.routes.draw do
  resources :articles

   root 'articles#index'

  post 'comments' => 'comments#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings

	def self.search(search)
		if search
			where("lower(title) LIKE ?", "%#{search.downcase}%")
					.order(created_at: :desc)
		else
			all
					.order(created_at: :desc)
		end
	end

	def increase_view_count
		self.view_count += 1
		self.save
	end

	def generate_tags(tags_string)
		tag_array = tags_string.split(/\s*,\s*/)
		tag_array.each do |tag_string|
			unless (tag_string.blank?)
				new_tag = (Tag.find_by_tag_name tag_string) || Tag.new(tag_name: tag_string)
				self.tags << new_tag
			end
		end
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :body, presence: true 
  validates :name, presence: true 
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	belongs_to :article
	belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search])

    if (params.has_key?(:tag))
      @tag = params[:tag]
      @articles = Tag.find_by_tag_name(@tag).articles
      flash[:notice] = "Articles which have #{@tag} tag"
    end

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article.increase_view_count
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    if !@article.is_editable
      respond_to do |format|
      format.html { redirect_to @article, notice: 'Article is not editable.' }
        format.json { render :show, status: :unprocessable_entity, location: @article }
      end
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.generate_tags(params[:tags])
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.is_editable
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @article, notice: 'Article is not editable.' }
        format.json { render :show, status: :unprocessable_entity, location: @article }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if (!@article.is_deletable)
      respond_to do |format|
        format.html { redirect_to articles_url, notice: "Cannot delete author's article." }
        format.json { head :no_content }
      end     
    else
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		respond_to do |format|
			if @comment.save
				format.json do
					render :json => {:success => @comment.valid?, :comment => @comment.body, :name => @comment.name }
				end
			else
				format.json do
					render :json => {:success => @comment.valid?, :errors => @comment.errors }
				end
			end
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :name, :article_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
  <div class="row">
    <div class="col-sm-offset-2 col-sm-8 col-xs-12">
      <div class="card">
        <div class="card-block">
        <h4 class="card-title"><%= link_to article.title, article_path(article) %></h4>
          <p class="card-text"><%= @markdown.render(article.body).html_safe %></p>
        </div>
        <div class="card-footer">
          <% if article.is_editable %>
          <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-warning'%>
          <% end %>
          <% if article.is_deletable %>
          <%= link_to 'Delete', article_path(article), :method => :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"}  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

  <ul>
    <% @article.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset class="form-group">
  <%= f.label :title %><br>
  <%= f.text_field :title, class: 'form-control', placeholder: 'Article title' %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :tags %><br>
  <%= text_field_tag :tags, nil, class: 'form-control', placeholder: 'tags - seperate by comma' %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :body %><br>
  <%= f.text_area :body, class: 'form-control', rows: '5' %>
</fieldset>

<div class="actions">
  <%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<%= render @articles %>
<br>

app/views/articles/new.html.erb
<h1 class="new-article-header">New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: 'btn' %>

app/views/articles/show.html.erb
<div class="container">
	<div class="center-block">
		<p id="notice"><%= notice %></p>
		<h1 class="title row">
			<%= @article.title %>
		</h1>
		<p class="viewcount row">
			<strong>View count:</strong>
			<%= @article.view_count %>
		</p>
    <div class="tags_list">
      <% @article.tags.each do |tag| %>
      <%= link_to tag.tag_name, articles_path(:tag => tag.tag_name), class: "article-tag" %>
          <% end %>
    </div>
		<div class="article_body">
			<%= @markdown.render(@article.body).html_safe  %>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-md-offset-2 col-md-8" id="comment_list">
					<div class="page-header">
						<h1><small class="float-right"><%= @article.comments.count %> comments</small> Comments </h1>
					</div> 
					<% if @article.comments.count > 0 %>
					<% @article.comments.order(:created_at).each do |comment| %>
					<div class="comments-list">
						<div class="media comment-body">
							<p class="float-right"><small><%= time_ago_in_words comment.created_at%></small></p>
							<div class="media-body">
								<h4 class="media-heading user_name"><%= comment.name %></h4>
								<div><%=  comment.body %></div>
							</div>
						</div>
					</div>	
					<% end %>
					<% end %>
				</div>
			</div>
		</div>

		<%= render 'comments/form' %>
		<div class="nav-buttons">
		<a href="#" class="btn btn-success" data-toggle="modal" data-target="#new-comment-modal">New comment</a> 
		<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-warning" %> 
		<%= link_to 'Back', articles_path, class: "btn btn-danger" %> 
		</div>
	</div>
</div>

app/views/comments/_form.html.erb
<div class="modal fade" id="new-comment-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for :comment, :url => comments_path,remote: true, html: { style: "display:inline;", class: "comment_form" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <div class="form-group">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.label :body, class: "control-label" %>
          <%= f.text_field :body, class: "form-control" %>
          <%= f.hidden_field :article_id, :value => @article.id %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<% content_for :head do %>
<script type="text/javascript">
  $(document).ready(function() {
    $(".comment_form").on('ajax:complete', function(_, response) {
      data = response.responseJSON;
      if (data.success){
        $(".errors").empty();
        commentList = $("#comment_list");
        var newcomment = "<div class=\"comments-list\"><div class=\"media comment-body\"><p class=\"float-right\"><small>" + "recent" + "</small></p><div class=\"media-body\"><h4 class=\"media-heading user_name\">User</h4><div>" + data.comment + "</div></div></div></div>";
        commentList.append(newcomment);
        $('#new-comment-modal').modal('hide');
      }
      else {
        $(".errors").empty();
        var keys = Object.keys(data.errors);

        for (var i = 0; i < keys.length; i++) {
          var message = data.errors[keys[i]];
          $(".errors").append("<li class=\"error_message\">" + keys[i] + ": " + message + "</li>");
  }
}
});
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <nav class="navbar navbar-dark bg-inverse">
    <div class="container-fluid">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
        &#9776;
      </button>
      <a class="navbar-brand" href="/">Tan's Blog</a>  
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <%= link_to 'New Article', new_article_path, class: "btn btn-success btn-new-article col-xs-12 col-sm-2"%>
        <%= form_tag articles_path, class: "form-inline navbar-form pull-sm-right",:method => 'get' do %>
        <%= text_field_tag :search, params[:search], class: "form-control col-xs-12 col-sm-8", placeholder: "Search" %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-success-outline btn-search form-control col-xs-12 col-sm-3" %>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
        © 2016 Copyright Tan Bui
      </div>
    </div>
  </footer>
</body>
</html>